SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C
ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY B.AUTHOR_NAME, A.CATEGORY
ORDER BY B.AUTHOR_ID ASC, A.CATEGORY DESC




# -- 코드를 입력하세요
# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) AS TOTAL_SALES
# FROM BOOK AS B
# JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN BOOK_SALES AS C ON B.BOOK_ID = C.BOOK_ID
# WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
# GROUP BY A.AUTHOR_NAME, B.CATEGORY
# ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;