WITH CAR_JOIN_T AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, B.START_DATE, B.END_DATE, C.DURATION_TYPE, C.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  C
    ON A.CAR_TYPE = C.CAR_TYPE
)

SELECT 
    DISTINCT CAR_ID,
    CAR_TYPE,
    ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_JOIN_T
WHERE CAR_TYPE IN ('세단', 'SUV')
    AND DURATION_TYPE = '30일 이상'
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30 >= 500000
    AND DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
