WITH RECURSIVE PARENT AS (
    SELECT ID, PARENT_ID, 0 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT B.ID, B.PARENT_ID, A.DEPTH + 1 AS DEPTH
    FROM PARENT A
    LEFT JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID
    WHERE A.ID IS NOT NULL
)   
SELECT 
       COUNT(1) AS COUNT, DEPTH GENERATION
  FROM PARENT
 WHERE ID IS NULL
 GROUP BY ID, DEPTH
 ORDER BY DEPTH