SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT A.ID, B.FISH_NAME, A.LENGTH, ROW_NUMBER() OVER(PARTITION BY A.FISH_TYPE ORDER BY A.LENGTH DESC) AS RN
    FROM FISH_INFO AS A
    JOIN FISH_NAME_INFO AS B
    ON A.FISH_TYPE = B.FISH_TYPE
) AS T
WHERE RN = 1
ORDER BY ID








# SELECT ID, FISH_NAME, LENGTH
# FROM (
#     SELECT A.ID, B.FISH_NAME, A.LENGTH, ROW_NUMBER() OVER(PARTITION BY A.FISH_TYPE ORDER BY A.LENGTH DESC) AS RN
#     FROM FISH_INFO A
#     JOIN FISH_NAME_INFO B
#     ON A.FISH_TYPE = B.FISH_TYPE
# ) AS T
# WHERE RN = 1
# ORDER BY ID ASC